# Python Circle CI configuration file
version: 2
jobs:
 build:
  docker:
   - image: circleci/python:3.7
  
  working_directory: ~/repo
  steps:
   # Step1: obtain repo from GitHub
   - checkout
   # Step2: 
   - run:
      name: install dependencies
      command: |
        python3 -m venv venv
        . venv/bin/activate
        pip install -r requirements.txt
   # Step3:
   - run:
      name: run tests
      command: |
        . venv/bin/activate
        flake8 --exclude=venv* --statistics
        pytest -v --cov=calculator
